import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Dashboardwraper from "./dashboardwraper";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["700", "800"],
});

export const metadata: Metadata = {
  title: "INVENTORY UPDATE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        {/* DashBoard Wraper */}
        <Dashboardwraper>{children}</Dashboardwraper>
      </body>
    </html>
  );
}
